// Next/React Imports
import type { GetServerSideProps, NextPage } from 'next'
import { useEffect, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
// Styles Import
import styles from '../styles/Home.module.css'
// Services Import
import { api } from './services/api'

const defaultEndPoint = 'https://rickandmortyapi.com/api/character'

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(defaultEndPoint)
  const data = await res.json()

  return {
    props: {
      data,
    }
  }
}

const Home: NextPage = ({ data }) => {
  const { info, results: defaultResults = [] } = data

  const [results, updateResults] = useState(defaultResults)
  
  const [page, updatePage] = useState({
    ...info, 
    current: defaultEndPoint
  })

  const { current } = page;

  useEffect(() => {
    if (current === defaultEndPoint) return

    const request = async () => {
      const res = await fetch(current)
      const nextData = await res.json()

      updatePage({
        current, 
        ...nextData.info
      })

      if ( nextData.info?.prev ) {
        updateResults(nextData.results)
        return
      }

      updateResults( (prev) => {
        return [
          ...prev,
          ...nextData.results
        ]
      })
    }

    request()
  }, [current])

  const handleLoadMore = async () => {
    updatePage( (prev) => {
      return {
        ...prev,
        current: page?.next
      }
    })
  }
  
  const handleOnSubmitSearch = async (e) => {
    e.preventDefault()

    const { currentTarget = {} } = e;
    const fields = Array.from(currentTarget?.elements)
    const fieldQuery = fields.find( field => field.name === 'query')

    const value = fieldQuery || ''
    const endpoint = `${defaultEndPoint}/?name=${value}`

    updatePage((prev) => {
      return {
        ...prev,
        current: endpoint
      }
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Wubba Lubba Dub Dub!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Wubba Lubba Dub Dub!
        </h1>

        <p className={styles.description}>
          Rick and Morty Wiki
        </p>

        <form action='search' onSubmit={handleOnSubmitSearch}>
          <input name='query' type='search'/>
          <button>Search</button>
        </form>

        <ul className={styles.grid}>
          {results.map((item) => {
            const { id, name, image } = item
            return (
              <li key={id}>
                <Link href={`/character/${id}`}>
                  <a className={styles.card}>
                    <img src={image} alt={`${name} Thumb`}/>
                    <h2>{ name }</h2>
                  </a>
                </Link>

              </li>
            )
          })}

        </ul>

        <p>
          <button type='button' onClick={handleLoadMore}>Load More</button>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
