import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../../styles/Home.module.css'

const defaultEndPoint = 'https://rickandmortyapi.com/api/character'

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
    const { id } = query
    const res = await fetch(`${defaultEndPoint}/${id}`)
    const data = await res.json()

    return {
        props: {
            data,
        }
    }
}

const Character: NextPage = ({ data }) => {
    const {
        name,
        image,
        gender,
        location,
        origin,
        species,
        status,
    } = data

    return (
        <div className={styles.container}>
            <Head>
                <title>{ name }</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    { name }
                </h1>

                <div>
                    <img src={image} alt={name} />
                </div>
                <div>
                    <h2>Character Details</h2>
                    <ul>
                        <li>
                            <strong>Name: {name}</strong>
                        </li>
                        <li>
                            <strong>Status: {status}</strong>
                        </li>
                        <li>
                            <strong>Gender: {gender}</strong>
                        </li>
                        <li>
                            <strong>Species: {species}</strong>
                        </li>
                        <li>
                            <strong>Location: {location?.name}</strong>
                        </li>
                        <li>
                            <strong>Originally From: {origin?.name}</strong>
                        </li>
                    </ul>
                    <Link href={`/`}><a>Back to all characters</a></Link>
                </div>
            </main>
        </div>
    )
}

export default Character
